### ISSUE TITLE
clarify intended behavior of `validate`

### ISSUE THREAD

**Issue by 0xdaem0n** [spruceid/siwe-py#25]
The `validate` and `verify` functions (unclear of the distinction, but appears to be discussed in https://github.com/spruceid/siwe-py/issues/24) has an inconsistent implementation in nearly every language. I am curious what the intended implementation is, totally understand that different languages have different idioms to adhere to.

* **Python**: the `validate` [function](https://github.com/spruceid/siwe-py/blob/5da519a2b5a8ae3fbc9d8a9d285a0a1dfc11a8fd/siwe/siwe.py#L195) does not return anything, merely raises an exception if there is an error in parsing. However, the docstring indicates an intended boolean return type (true if ok, false otherwise). 
* **Javascript**: the [equivalent validate function](
https://github.com/spruceid/siwe/blob/da5bd2cd56feb73c98b9710a31227f696967b21e/lib/client.ts#L226) returns `{Promise<SiweMessage>} This object if valid.`, which is a parsed message with all the message's fields.
* **Rust**: my read of the [verify function](https://github.com/spruceid/siwe-rs/blob/main/src/lib.rs#L236) (not `validate`) is that it returns the publickey, if valid, and throws an error otherwise. 
* **Golang**: [verify function](https://github.com/spruceid/siwe-go/blob/63b6ad5a0e4c3921643c5ab0ae63e1eaaa10d7fc/siwe.go#L243) looks to be same as in Rust
* **Ruby**: I think [this function](https://github.com/spruceid/siwe-ruby/blob/main/lib/siwe/message.rb) returns true if valid, and raises an exception otherwise.
* **Elixir**: AFAICT [this implementation](https://github.com/spruceid/siwe-ex/blob/7cadb52f52b67af2c86564bb28cdcebada6f1544/native/siwe_ex/src/lib.rs#L129) actually does return true if valid and false otherwise, as it catches any exceptions to finally return a boolean.

In particular, Javascript looks to be the outlier with its behavior - it does validate the message but _additionally_ returns the message. However, it's also the language with the most adoption / usage, so I assumed it was the 'canonical' approach.

Happy to help with the changes if we can confirm the desired behavior, thanks for working on the protocol!

**Comment by awoie** [comment]
We are currently harmonizing our APIs across languages (should be finished this week) and we can then revisit this issue.

**Comment by sbihel** [comment]
The naming is now unified accross the libraries, #27 for the Python one. `verify` is to verify the signature, nonce, etc. `validate` if present (it is a constructor in most languages) validates the formatting of a message.

As for the return type, it simply depends on what the underlying ethereum/secp256k1 library returns, and the language's idioms.
