### ISSUE TITLE
Not able to import siwe

### ISSUE THREAD

**Issue by dhruvildave22** [spruceid/siwe-py#28]
Hello,
I want to use siwe for one of my project in python. However i am having an issue. When i try to import siwe in file it gives me error.
I tried to import in different ways.
```
from siwe.siwe import SiweMessage
ModuleNotFoundError: No module named 'siwe.siwe'; 'siwe' is not a package
```
```
from siwe import siwe
ImportError: cannot import name 'siwe' from 'siwe'
```
and used this 
```
siwe.SiweMessage({})
```

but it did not work.
At last i used this 
```
import siwe
```
and it worked but how do i access `SiweMessage` and other classes coming from siwe library. 
Please Help.

Thanks
Dhruvil Dave

**Comment by sbihel** [comment]
Looks like the namespacing is not what I expected. Although it seems `from siwe import siwe` should work withing the repl, and `from siwe.siwe import ...` has been used in other projects. May I ask what version of Python you're using? And maybe your OS/arch as well?

#29 will make the package behave as one would expect (`from siwe import SiweMessage`) and should be released with the 2.0 version which should come in the next few days.

**Comment by dhruvildave22** [comment]
I am using python 3.7 on macOS Monterey(M1 chip)

**Comment by w4ll3** [comment]
It should be release next Monday with the rest of the siwe libraries
