### ISSUE TITLE
Update Pydantic version to > 2.0.0

### ISSUE THREAD

**Issue by ljiatu** [spruceid/siwe-py#39]
Pydantic released V2 on 6/30, but this library is still depending on <2.0.0. Would be great to have it updated.

Thanks in advance!

**Comment by sambarnes** [comment]
while i agree with #40 too

i think this pr is the minimum needed to get onto pydantic 2.0
https://github.com/spruceid/siwe-py/pull/41

**Comment by sbihel** [comment]
This has been published as v2.3.0
