### ISSUE TITLE
Refactor CustomDateField

### ISSUE THREAD

**Issue by ameyarao98** [spruceid/siwe-py#50]
The current implementation is a bit hacky, and would not work with pydantic v2. It could be made into a `datetime` object, which Pydantic can parse from various formats,making it easier to create a message if not using a string. There should still however be a manual check when parsed from a string that it fits the ISO standard. Some custom logic (or someting in dateutil?) may be needed to turn the datetime into the proper format

**Comment by fubuloubu** [comment]
I have been using this w/ Pydantic V2:

```py
def iso_format(dt: datetime) -> str:
    return dt.isoformat()


UTCTimestamp = Annotated[
    datetime,
    PlainSerializer(iso_format, return_type=str),
]
```
