### ISSUE TITLE
Multisigs/Gnosis safe wallets do not work out of the box

### ISSUE THREAD

**Issue by UTkzhang** [spruceid/siwe-py#63]
In verify function,
```
   try:
      address = w3.eth.account.recover_message(message, signature=signature)
  except ValueError:
      address = None
  except eth_utils.exceptions.ValidationError as e:
      raise InvalidSignature from None
```

This recover_message runs into the ValidationError: "Unexpected recoverable signature length: Expected 65, but got 130 bytes" for a 2 signer signature, and raises Exception with cause None instead of going on to check_contract_wallet_signature.

This should not be the behaviour and causes all multisig signers to not work with SIWE lib out of the box. 

Reproduce: try signing a SIWE message with 2 signers multisig like safe wallet and see if verify is able to authenticate it.

Proposed fix:
if sig is not 65, instead of raising, continue to check check_contract_wallet_signature eip1271 directly, because it is either a multisig or the user passed in the wrong string somehow. Only raise if check_contract_wallet_signature fails.

**Comment by sbihel** [comment]
In your call to the `verify` function, do you supply a `provider`? Here is an example with a test for contract wallets https://github.com/spruceid/siwe-py/blob/53f71d805c39d6118d0f47620940bbe2c5699779/tests/test_siwe.py#L82

**Comment by UTkzhang** [comment]
Yes the provider isn’t the issue - it’s the fact that multi sig contract wallets have non standard signature lengths which aren’t handled corrected at the moment

**Comment by UTkzhang** [comment]
In the sample test json, I see the sig is a single signer from a smart contract wallet. Try a multi signer variant (2 signers for example).

**Comment by sbihel** [comment]
I'm fairly certain that the error about the signature length is a red herring as it is the reason why the EIP-191 failed, but it doesn't mean EIP-1271 wasn't tried (it's unfortunate, but there's no way of knowing in advance what "kind" of signature it is). 

Would you be able to provide an example? You mentioned Safe and it does support EIP-1271, so I'm curious what is the root cause.

**Comment by UTkzhang** [comment]
Yea my point is exactly that - the standard recover fails, the eip1271 is implemented correctly, no issues there.

The bug is that due to multi sig wallets returning a signature that is of non standard length, it errors on the recover method and never makes it to the subsequent eip1271 verification.

As highlighted in original issue:
This recover_message runs into the ValidationError: "Unexpected recoverable signature length: Expected 65, but got 130 bytes" for a 2 signer signature, and raises Exception with cause None instead of going on to check_contract_wallet_signature.

So it is the eip191 failing, but it is also confirmed that the eip1271 isn’t tried because it raises on this recover_message line instead of continuing like all other cases.

**Comment by UTkzhang** [comment]
```
try:
      address = w3.eth.account.recover_message(message, signature=signature) # fails due to wrong sig length
  except ValueError:
      address = None
  except eth_utils.exceptions.ValidationError as e:
      raise InvalidSignature from None # raised to upper level and never makes it to the next line for eip1271
```

**Comment by sbihel** [comment]
I looked a bit more into it and we already have a test for EIP-1271 with a signature that's 66 bytes long https://github.com/spruceid/siwe/blob/4290e1fb3702c97ffee16112492216ad4c4654c1/test/eip1271.json#L8. Would you be able to provide an example because I don't know how to reproduce it right now?
